name: C/C++ CI - Build + CodeQuality 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: Build_CodeQuality
      run: gcc HelloWorld.c -o HelloWorld
